### PR TITLE
Dockerise

### PR DESCRIPTION
**Pull request by ohmydevops**
Base Dockerfile based on `python:3.10.1`, is it right? is this version suitable for running tracevic?

### CODE REVIEW

**Comment by ohmydevops** [comment]
- [ ] handle data persistent (docker volume)

**Comment by ohmydevops** [comment]
How can i change `output` dir (for example with ENVs)?

**Comment by ohmydevops** [comment]
Test all things with docker image:

- [ ] Run DNS commands
- [ ] Run Packets commands
- [ ] Run RIPE commands
- [ ] Run File command
- [ ] Run help command

**Review by xhdix — APPROVED** [review]
LGTM, thanks a bunch! <3

**Pull request merged**
