### PR TITLE
feature: unittests

### PR DESCRIPTION
**Pull request by RYNEQ**
This is a tryout to add UnitTests to `tracevis` 
we can now test by `python -m unittest discover test -b`
It is not complete yet so PR should wait until most of important tests be complete

### CODE REVIEW

**Review by bassosimone — DISMISSED** [review]
Thanks for working on unit tests to ensure the CLI API does not break unexpectedly!

🙏 🥳 🐳 👍

**Comment by bassosimone** [comment]
>  It is not complete yet so PR should wait until most of important tests be complete

Yeah. It's already a good start to have these unit tests and we can add more. Perhaps, it would be cool to add a GitHub action for running tests automatically at every commit and PR before merging, if you have time for that!

**Comment by RYNEQ** [comment]
Thanks for the review and comments
Yes we should add more tests specially for core functionalities but it can be progressive and every new test can be added to previous ones in the future  
So it is a good idea to start having actions for the ones already exist

I also think having a code coverage test in actions can help and show how much of the codebase is under test

**Comment by RYNEQ** [comment]
- `test_config_file` unittest fixed for missing keys in config file
Now it tests against existing keys in config file and ignores the rest (the rest of keys are defaults which previously tested in `test_defaults`)

- Added coverage package to make code covarage test possible
adding `coverage` before test command makes test report and `coverage report` shows it

**Review by bassosimone — CHANGES_REQUESTED** [review]
🥳 Thanks for the improved tests! Could you also commit a github action that runs tests at every commit and pull request? 🙏

**Comment by RYNEQ** [comment]
> partying_face Thanks for the improved tests! Could you also commit a github action that runs tests at every commit and pull request? pray

Hi @bassosimone , I added the unittest action file.  
for code coverage test we can have similar action file wich only can show `pass` or `fail` result. so to show coverage percent in `README.md` we need to generate a custom badge. we have three options:  
- Use cloud test providers (e.g. codecov) which will need GH_TOKEN to generate badge for us  
- Calculate percentage using simple bash and use badge generator URLs like googleapi or shields.io, which need to include external URL in `README.md` and update README file on every push (this adds additional change to README which is  unrelated to commit subject)
- Generate badge using python in action file and store its image in somewhere (e.g. `.github` dir) and use it in `README.md`  

What is your opinion? Which one is the best approach?

**Comment by bassosimone** [comment]
@RYNEQ At OONI, we generally use codecov or coveralls and link their badge, which, as you say, requires to setup some form of communication between GitHub and one of those services. The other two options that you mention strike me as a bit more work, so perhaps we should try to avoid using them, unless there's some reason not to trust an external coverage service. In such a case, I would just ignore generating the badge and make hack some code to make the GitHub action fail if the coverage decreases by more than, say, 0.5%.

**Review by bassosimone — DISMISSED** [review]
(Your subsequent changes LGTM! 🐳 )

**Review by xhdix — APPROVED** [review]
Thank you @RYNEQ and @bassosimone! :heart: :hibiscus: 
I'm going to merge this. There will be follow-up PR for adding Coveralls workflow.

**Pull request merged**
